apiVersion: v1
kind: Service

metadata:
  name: observability-app-service
  namespace: observability
  labels:
    app: observability-app

spec:
  selector:
    app: observability-app

  ports:
    - name: http
      port: 80
      targetPort: 8000

  type: ClusterIP
